name: GraalVM Native Image builds
on: [push, pull_request]
jobs:
  build:
    name: Spring Native on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '22'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Build and run a Spring Native app
        run: |
          mvn --no-transfer-progress -Pnative native:compile

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: demo-${{ matrix.os }}
          path: |
            target/demo